version: '3'
services:
    fkafka-application-example:
        build:
            context: .
            dockerfile: DockerfileExample
        ports:
            - '8080:8080'
        stdin_open: true
        tty: true
        environment:
            GROUP_ID: arch-kafkaApplication-example-local-38
